delete from schema_migrations;
drop table if exists delayed_jobs; 
drop table if exists filters; 
drop table if exists users;
drop table if exists search_actions; 
drop table if exists search_details;
drop table if exists search_types; 
drop table if exists search_statuses; 
drop table if exists searches; 
drop table if exists share_activities;
drop table if exists priority_searches;